### ISSUE TITLE
Create a github page for BiasClaculator-Pro repository

### ISSUE THREAD

**Issue by nitin-bitswilp** [prabhus489/BiasCalculator-Pro#13]
Similar to the HTML page we created for the previous assignment, we need to create a Github page for this repository.

**Comment by prabhus489** [comment]
The repository codes are hosted in the below githup pages

https://prabhus489.github.io/BiasCalculator-Pro/

![image](https://user-images.githubusercontent.com/43057160/167260857-89e9c4a9-46b0-4703-b1ef-7780e5793e2d.png)


![image](https://user-images.githubusercontent.com/43057160/167260844-a1d2d85a-cde0-4b09-b23d-081ee6d77782.png)
